### List personal trading history
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("GET", request);
%}

GET {{api_v4}}/spot/my_trades
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### List spot accounts
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("GET", request);
%}

GET {{api_v4}}/spot/accounts
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### Query account book
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("GET", request);
%}

GET {{api_v4}}/spot/account_book
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### List orders
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("GET", request);
%}

GET {{api_v4}}/spot/orders?currency_pair=VAI_USDT&status=finished
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### Create an order
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("POST", request);
%}

POST {{api_v4}}/spot/orders
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json

{
  "currency_pair": "BTC_USDT",
  "type": "limit",
  "side": "buy",
  "amount": "0.001",
  "price": "60000"
}


### Cancel a single order
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("DELETE", request);
%}

DELETE {{api_v4}}/spot/orders/123456?currency_pair=BTC_USDT
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### Get a single order
< {%
  import {gen_sign} from 'sign.js'
  gen_sign("GET", request);
%}

GET {{api_v4}}/spot/orders/745504484392?currency_pair=BTC_USDT
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json

