### List personal trading history
< {%
  const pattern = RegExp("^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?");
  const url = request.url.tryGetSubstituted();
  const matches =  url.match(pattern);
  const method = "GET";
  const path = matches[5];
  const query = matches[7] || "";
  const hexedHashedBody = crypto.sha512().updateWithText(request.body.tryGetSubstituted() || "").digest().toHex();
  const timestamp = Math.floor(Date.now() / 1000).toFixed();
  const payloadToSign = `${method}\n${path}\n${query}\n${hexedHashedBody}\n${timestamp}`;
  const apiSecret = request.environment.get("api_secret");
  const sign = crypto.hmac.sha512().withTextSecret(apiSecret).updateWithText(payloadToSign).digest().toHex();
  request.variables.set("timestamp", timestamp);
  request.variables.set("sign", sign);
%}

GET {{api_v4}}/spot/my_trades
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json


### Query account book
< {%
  const pattern = RegExp("^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?");
  const url = request.url.tryGetSubstituted();
  const matches =  url.match(pattern);
  const method = "GET";
  const path = matches[5];
  const query = matches[7] || "";
  const hexedHashedBody = crypto.sha512().updateWithText(request.body.tryGetSubstituted() || "").digest().toHex();
  const timestamp = Math.floor(Date.now() / 1000).toFixed();
  const payloadToSign = `${method}\n${path}\n${query}\n${hexedHashedBody}\n${timestamp}`;
  const apiSecret = request.environment.get("api_secret");
  const sign = crypto.hmac.sha512().withTextSecret(apiSecret).updateWithText(payloadToSign).digest().toHex();
  request.variables.set("timestamp", timestamp);
  request.variables.set("sign", sign);
%}

GET {{api_v4}}/spot/account_book
KEY: {{api_key}}
SIGN: {{sign}}
Timestamp: {{timestamp}}
Content-Type: application/json

