/*
 * BitMEX API
 * ## REST API for the BitMEX Trading Platform  [View Changelog](/app/apiChangelog)  ----  #### Getting Started  Base URI: [https://www.bitmex.com/api/v1](/api/v1)  ##### Fetching Data  All REST endpoints are documented below. You can try out any query right from this interface.  Most table queries accept `count`, `start`, and `reverse` params. Set `reverse=true` to get rows newest-first.  Additional documentation regarding filters, timestamps, and authentication is available in [the main API documentation](/app/restAPI).  *All* table data is available via the [Websocket](/app/wsAPI). We highly recommend using the socket if you want to have the quickest possible data without being subject to ratelimits.  ##### Return Types  By default, all data is returned as JSON. Send `?_format=csv` to get CSV data or `?_format=xml` to get XML data.  ##### Trade Data Queries  *This is only a small subset of what is available, to get you started.*  Fill in the parameters and click the `Try it out!` button to try any of these queries.  * [Pricing Data](#!/Quote/Quote_get)  * [Trade Data](#!/Trade/Trade_get)  * [OrderBook Data](#!/OrderBook/OrderBook_getL2)  * [Settlement Data](#!/Settlement/Settlement_get)  * [Exchange Statistics](#!/Stats/Stats_history)  Every function of the BitMEX.com platform is exposed here and documented. Many more functions are available.  ##### Swagger Specification  [⇩ Download Swagger JSON](swagger.json)  ----  ## All API Endpoints  Click to expand a section. 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@bitmex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.knowm.xchange.bitmex.dto;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BitmexUserCommission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-06T17:10:23.689Z")
public class BitmexUserCommission {
  @SerializedName("makerFee")
  private Double makerFee = null;

  @SerializedName("takerFee")
  private Double takerFee = null;

  @SerializedName("settlementFee")
  private Double settlementFee = null;

  @SerializedName("maxFee")
  private Double maxFee = null;

  public BitmexUserCommission makerFee(Double makerFee) {
    this.makerFee = makerFee;
    return this;
  }

   /**
   * Get makerFee
   * @return makerFee
  **/
  @ApiModelProperty(value = "")
  public Double getMakerFee() {
    return makerFee;
  }

  public void setMakerFee(Double makerFee) {
    this.makerFee = makerFee;
  }

  public BitmexUserCommission takerFee(Double takerFee) {
    this.takerFee = takerFee;
    return this;
  }

   /**
   * Get takerFee
   * @return takerFee
  **/
  @ApiModelProperty(value = "")
  public Double getTakerFee() {
    return takerFee;
  }

  public void setTakerFee(Double takerFee) {
    this.takerFee = takerFee;
  }

  public BitmexUserCommission settlementFee(Double settlementFee) {
    this.settlementFee = settlementFee;
    return this;
  }

   /**
   * Get settlementFee
   * @return settlementFee
  **/
  @ApiModelProperty(value = "")
  public Double getSettlementFee() {
    return settlementFee;
  }

  public void setSettlementFee(Double settlementFee) {
    this.settlementFee = settlementFee;
  }

  public BitmexUserCommission maxFee(Double maxFee) {
    this.maxFee = maxFee;
    return this;
  }

   /**
   * Get maxFee
   * @return maxFee
  **/
  @ApiModelProperty(value = "")
  public Double getMaxFee() {
    return maxFee;
  }

  public void setMaxFee(Double maxFee) {
    this.maxFee = maxFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BitmexUserCommission userCommission = (BitmexUserCommission) o;
    return Objects.equals(this.makerFee, userCommission.makerFee) &&
        Objects.equals(this.takerFee, userCommission.takerFee) &&
        Objects.equals(this.settlementFee, userCommission.settlementFee) &&
        Objects.equals(this.maxFee, userCommission.maxFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(makerFee, takerFee, settlementFee, maxFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BitmexUserCommission {\n");
    
    sb.append("    makerFee: ").append(toIndentedString(makerFee)).append("\n");
    sb.append("    takerFee: ").append(toIndentedString(takerFee)).append("\n");
    sb.append("    settlementFee: ").append(toIndentedString(settlementFee)).append("\n");
    sb.append("    maxFee: ").append(toIndentedString(maxFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

