### Get Coin Info
GET {{api_host}}/api/v2/spot/public/coins?coin=usdt


### Get OrderBook Depth
GET {{api_host}}/api/v2/spot/market/orderbook?symbol=btcusdt


### Get Symbol Info
GET {{api_host}}/api/v2/spot/public/symbols


### Get Ticker Information
GET {{api_host}}/api/v2/spot/market/tickers


### Get Account Information
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/account/info
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Account assets
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/account/assets
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Order Info
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/trade/orderInfo?orderId=1213530920130613257
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Place Market Buy Order
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/spot/trade/place-order
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json

{
  "symbol": "BGBUSDT",
  "side": "buy",
  "orderType": "market",
  "size": "2",
  "clientOid": "{{$random.uuid}}"
}


### Place Market Sell Order
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
POST {{api_host}}/api/v2/spot/trade/place-order
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}
Content-Type: application/json

{
  "symbol": "BGBUSDT",
  "side": "sell",
  "orderType": "market",
  "size": "3",
  "clientOid": "{{$random.uuid}}"
}


### Get History Orders
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/trade/history-orders
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Fills
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/trade/fills?symbol=BTCUSDT
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Transfer Record
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/account/transferRecords?coin=USDT&fromType=spot&endTime=1727904561971
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get MainSub Transfer Record
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/account/sub-main-trans-record
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Deposit Records
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/wallet/deposit-records?startTime=1721643200000&endTime=1727970869665
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


### Get Withdrawal Records
< {%
  import {gen_sign} from 'sign.js'
  gen_sign(request);
%}
GET {{api_host}}/api/v2/spot/wallet/withdrawal-records?startTime=1721643200000&endTime=1727970869665
ACCESS-KEY: {{api_key}}
ACCESS-SIGN: {{sign}}
ACCESS-TIMESTAMP: {{timestamp}}
ACCESS-PASSPHRASE: {{api_passphrase}}


