### Subscribe instrument
WEBSOCKET {{base_url}}/realtime
Content-Type: application/json

{
  "op": "subscribe",
  "args": [
    "instrument"
  ]
}

### Unsubscribe instrument
WEBSOCKET {{base_url}}/realtime
Content-Type: application/json

{
  "op": "unsubscribe",
  "args": [
    "instrument"
  ]
}


