# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Format on Pull Request

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Format Code
      run: |
        mvn com.coveo:fmt-maven-plugin:format
        git config user.name "${GITHUB_ACTOR} (actions)"
        git config user.email nobody@knowm.org
        if [[ `git status --porcelain` ]]; then git commit -am "Code format [skip ci]" && git push; fi
