on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        include:
          - java: '21'
            experimental: true
          - java: '25'
            experimental: true
    continue-on-error: ${{ matrix.experimental || false }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with maven
        run: mvn --projects .,xchange-core,${{ inputs.module-name }} -DskipTests -Dmaven.javadoc.skip -DskipIntegrationTests=false verify
